### PR TITLE
feat: tidy up the grammar and repo

### PR DESCRIPTION
**Pull request by amaanq**
Title, I improved it a bit to make query capturing lighter and easier. Hope this can be merged then I'll add to nvim-treesitter!

### CODE REVIEW

**Comment by Decodetalkers** [comment]
Thank you very much..

**Comment by Decodetalkers** [comment]
But, before I set identifier to to type.definition
```
(identifier) @type.definition
```
add this line will be better?

**Comment by amaanq** [comment]
No, that's a very elusive capture and is ONLY for things like

`typedef Foo = Bar`
`type Foo Bar`

where type/typedef are `@type.definition`

**Comment by Decodetalkers** [comment]
> No, that's a very elusive capture and is ONLY for things like
> 
> `typedef Foo = Bar` `type Foo Bar`
> 
> where type/typedef are `@type.definition`

image
but I think the identifier should have a highlight, like the set.. but now it is ok

**Comment by amaanq** [comment]
how about `@preproc`?

**Comment by amaanq** [comment]
and do you mind adding me as a contributor/collaborator? (I do maintain ~15 parsers if that helps :) )

**Comment by Decodetalkers** [comment]
> and do you mind adding me as a contributor/collaborator? (I do maintain ~15 parsers if that helps :) )

I am glad that you can help me :)

**Comment by amaanq** [comment]
No problem, so..is `@preproc` ok for the first identifier in a command? I plan to submit this to nvim-treesitter soon

**Comment by Decodetalkers** [comment]
> No problem, so..is `@preproc` ok for the first identifier in a command? I plan to submit this to nvim-treesitter soon

I think is ok,if they accept

**Pull request merged**
